using System.Collections.Immutable;
using System.Text;

namespace Davish.Sendr.Generators;

/// <summary>
/// Renders the <c>GeneratedSender</c> class and the <c>UseGenerators()</c> registration method
/// as plain C# text.
/// </summary>
internal static class SourceBuilder
{
    public static string Build(ImmutableArray<HandlerModel> models)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Davish.Sendr.Generators. Do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        sb.AppendLine("namespace Davish.Sendr.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class GeneratedSender : global::Davish.Sendr.ISender, global::Davish.Sendr.IStreamSender");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedSender(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();

        AppendSendAsync(sb, models.Where(m => m.Kind == HandlerKind.Request).ToImmutableArray());
        sb.AppendLine();
        AppendSendAsyncWithResponse(sb, models.Where(m => m.Kind == HandlerKind.RequestResponse).ToImmutableArray());
        sb.AppendLine();
        AppendSendStream(sb, models.Where(m => m.Kind == HandlerKind.Stream).ToImmutableArray());

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace Davish.Sendr");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated Davish.Sendr registration. Discovers every <c>IRequestHandler</c>/");
        sb.AppendLine("    /// <c>IStreamRequestHandler</c> in this compilation and installs a reflection-free");
        sb.AppendLine("    /// <c>ISender</c>/<c>IStreamSender</c> in their place. Generated by Davish.Sendr.Generators.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SendrOptionsGeneratedExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Installs the generated, reflection-free <c>ISender</c>/<c>IStreamSender</c> and registers");
        sb.AppendLine("        /// every handler (and <c>[Decorate&lt;...&gt;]</c> pipeline) discovered in this compilation.");
        sb.AppendLine("        /// Call from <c>AddSendr</c>: <c>services.AddSendr(o =&gt; o.UseGenerators())</c>.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::Davish.Sendr.SendrOptions UseGenerators(this global::Davish.Sendr.SendrOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            options.UseSender<global::Davish.Sendr.Generated.GeneratedSender>();");
        sb.AppendLine("            var services = options.Services;");
        sb.AppendLine();

        var emittedHandlers = new HashSet<string>();
        foreach (var model in models)
        {
            if (emittedHandlers.Add(model.HandlerType))
                sb.AppendLine($"            services.AddTransient<{model.HandlerType}>();");
        }

        var emittedDecorators = new HashSet<string>();
        foreach (var model in models)
            foreach (var decorator in model.Decorators)
            {
                if (emittedDecorators.Add(decorator.TypeName))
                    sb.AppendLine(
                        $"            global::Microsoft.Extensions.DependencyInjection.Extensions." +
                        $"ServiceCollectionDescriptorExtensions.TryAddTransient(services, typeof({decorator.TypeName}));");
            }

        sb.AppendLine();
        sb.AppendLine("            return options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // Dispatch is a static (built once, shared across every scope) Dictionary<Type, Func<...>>
    // rather than `switch (request) { case T1: ... case T2: ... }`, so a compilation with many
    // handlers still gets O(1) hash lookup instead of O(n) sequential type tests.

    private static void AppendSendAsync(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.IRequest, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _requestHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [typeof({model.RequestType})] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IRequestHandler<{model.RequestType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IRequestDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task SendAsync(");
        sb.AppendLine("            global::Davish.Sendr.IRequest request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_requestHandlers.TryGetValue(request.GetType(), out var handler))");
        sb.AppendLine("                return handler(_sp, request, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                $\"Davish.Sendr: no IRequestHandler<{request.GetType()}> is registered.\");");
        sb.AppendLine("        }");
    }

    private static void AppendSendAsyncWithResponse(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.IRequest, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _requestResponseHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [typeof({model.RequestType})] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IRequestHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IRequestDecorator.WithResponse");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // Task<{ResponseType}> is-a Task, no cast needed here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task<TResponse> SendAsync<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IRequest<TResponse> request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_requestResponseHandlers.TryGetValue(request.GetType(), out var handler))");
        sb.AppendLine("                return (global::System.Threading.Tasks.Task<TResponse>)handler(_sp, request, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                $\"Davish.Sendr: no IRequestHandler<{request.GetType()}, {typeof(TResponse)}> is registered.\");");
        sb.AppendLine("        }");
    }

    private static void AppendSendStream(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, object, " +
                      "global::System.Threading.CancellationToken, object>> _streamHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [typeof({model.RequestType})] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IStreamRequestHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IStreamRequestDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // IAsyncEnumerable<{ResponseType}> is a reference type, boxed as object here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> SendStream<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IStreamRequest<TResponse> request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (_streamHandlers.TryGetValue(request.GetType(), out var handler))");
        sb.AppendLine("                return (global::System.Collections.Generic.IAsyncEnumerable<TResponse>)handler(_sp, request, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                $\"Davish.Sendr: no IStreamRequestHandler<{request.GetType()}, {typeof(TResponse)}> is registered.\");");
        sb.AppendLine("        }");
    }

    private static void AppendDecoratorLocals(StringBuilder sb, HandlerModel model, string decoratorInterface)
    {
        for (var i = 0; i < model.Decorators.Length; i++)
        {
            sb.AppendLine($"                var d{i} = ({decoratorInterface})" +
                           $"sp.GetRequiredService<{model.Decorators[i].TypeName}>();");
        }
    }

    /// <summary>
    /// Wraps <paramref name="innermostCall"/> with the model's decorators, outermost-first,
    /// mirroring the ordering of <c>x.Decorator.With&lt;T&gt;()</c> chains: the first
    /// <c>[Decorate]</c> declared is the outermost layer and runs first.
    /// </summary>
    private static string BuildComposedCall(HandlerModel model, string innermostCall)
    {
        var call = innermostCall;
        for (var i = model.Decorators.Length - 1; i >= 0; i--)
            call = $"d{i}.HandleAsync(r, () => {call}, cancellationToken)";
        return call;
    }
}
