using System.Collections.Immutable;
using System.Text;

namespace Davish.Sendr.Generators;

/// <summary>
/// Renders the <c>GeneratedSender</c> class and the <c>UseGenerators()</c> registration method
/// as plain C# text.
/// </summary>
internal static class SourceBuilder
{
    public static string Build(ImmutableArray<HandlerModel> models, bool hasNotificationSupport)
    {
        var senderModels = models.Where(m => m.Kind != HandlerKind.Notification).ToImmutableArray();
        var notificationModels = models.Where(m => m.Kind == HandlerKind.Notification).ToImmutableArray();

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Generated by Davish.Sendr.Generators. Do not edit by hand.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        sb.AppendLine("namespace Davish.Sendr.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed class GeneratedSender : global::Davish.Sendr.ISender");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedSender(global::System.IServiceProvider sp) => _sp = sp;");
        sb.AppendLine();
        // The manual AddRequestHandler/etc. path can say "call AddRequestHandler<...>()" because
        // that's genuinely how it resolves handlers, through DI. GeneratedSender never does — its
        // dispatch tables are baked in at compile time — so pointing users at AddRequestHandler
        // here would be actively misleading. The real, generator-specific causes are: the handler
        // lives in a different project (the generator only sees THIS compilation's own syntax
        // trees, never an already-compiled ProjectReference's), it's a struct/record struct
        // (SENDR004) or open generic (SENDR003), or it just isn't implemented yet.
        sb.AppendLine("        private static string NotDiscovered(string handlerDescription) =>");
        sb.AppendLine("            $\"Davish.Sendr: no {handlerDescription} was discovered by the source generator. \" +");
        sb.AppendLine("            \"Make sure the handler is a class or record (not struct/record struct or open generic) \" +");
        sb.AppendLine("            \"declared in this project's own compilation — the generator can't see a handler from a \" +");
        sb.AppendLine("            \"referenced project, even via ProjectReference — or register it manually instead of \" +");
        sb.AppendLine("            \"relying on UseGenerators().\";");
        sb.AppendLine();

        AppendSendAsync(sb, senderModels.Where(m => m.Kind == HandlerKind.Request).ToImmutableArray());
        sb.AppendLine();
        AppendSendAsyncWithResponse(sb, senderModels.Where(m => m.Kind == HandlerKind.RequestResponse).ToImmutableArray());
        sb.AppendLine();
        AppendSendStream(sb, senderModels.Where(m => m.Kind == HandlerKind.Stream).ToImmutableArray());
        sb.AppendLine();
        AppendSendAsyncCommand(sb, senderModels.Where(m => m.Kind == HandlerKind.Command).ToImmutableArray());
        sb.AppendLine();
        AppendSendAsyncCommandWithResponse(sb, senderModels.Where(m => m.Kind == HandlerKind.CommandResponse).ToImmutableArray());
        sb.AppendLine();
        AppendSendAsyncQuery(sb, senderModels.Where(m => m.Kind == HandlerKind.Query).ToImmutableArray());

        sb.AppendLine("    }");

        if (hasNotificationSupport)
        {
            sb.AppendLine();
            AppendGeneratedPublisher(sb, notificationModels);
        }

        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("namespace Davish.Sendr");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated Davish.Sendr registration. Discovers every <c>IRequestHandler</c>/");
        sb.AppendLine("    /// <c>IStreamRequestHandler</c> in this compilation and installs a reflection-free");
        sb.AppendLine("    /// <c>ISender</c>/<c>IStreamSender</c> in their place. Generated by Davish.Sendr.Generators.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class SendrOptionsGeneratedExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Installs the generated, reflection-free <c>ISender</c>/<c>IStreamSender</c> and registers");
        sb.AppendLine("        /// every handler (and <c>[Decorate&lt;...&gt;]</c> pipeline) discovered in this compilation.");
        sb.AppendLine("        /// Call from <c>AddSendr</c>: <c>services.AddSendr(o =&gt; o.UseGenerators())</c>.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        public static global::Davish.Sendr.SendrOptions UseGenerators(this global::Davish.Sendr.SendrOptions options)");
        sb.AppendLine("        {");
        sb.AppendLine("            options.UseSender<global::Davish.Sendr.Generated.GeneratedSender>();");
        sb.AppendLine("            var services = options.Services;");
        sb.AppendLine();

        AppendHandlerAndDecoratorRegistrations(sb, senderModels);

        sb.AppendLine();
        sb.AppendLine("            return options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        if (hasNotificationSupport)
        {
            sb.AppendLine();
            AppendNotificationOptionsGeneratedExtensions(sb, notificationModels);
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendHandlerAndDecoratorRegistrations(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        var emittedHandlers = new HashSet<string>();
        foreach (var model in models)
        {
            if (emittedHandlers.Add(model.HandlerType))
                sb.AppendLine($"            services.AddTransient<{model.HandlerType}>();");
        }

        var emittedDecorators = new HashSet<string>();
        foreach (var model in models)
            foreach (var decorator in model.Decorators)
            {
                if (emittedDecorators.Add(decorator.TypeName))
                    sb.AppendLine(
                        $"            global::Microsoft.Extensions.DependencyInjection.Extensions." +
                        $"ServiceCollectionDescriptorExtensions.TryAddTransient(services, typeof({decorator.TypeName}));");
            }
    }

    // Dispatch is a static (built once, shared across every scope) Dictionary<Type, Func<...>>
    // rather than `switch (request) { case T1: ... case T2: ... }`, so a compilation with many
    // handlers still gets O(1) hash lookup instead of O(n) sequential type tests.

    private static void AppendSendAsync(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.IRequest, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _requestHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [typeof({model.RequestType})] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IRequestHandler<{model.RequestType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IRequestDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task SendAsync(");
        sb.AppendLine("            global::Davish.Sendr.IRequest request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(request));");
        sb.AppendLine();
        sb.AppendLine("            if (_requestHandlers.TryGetValue(request.GetType(), out var handler))");
        sb.AppendLine("                return handler(_sp, request, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                NotDiscovered($\"IRequestHandler<{request.GetType()}>\"));");
        sb.AppendLine("        }");
    }

    private static void AppendSendAsyncWithResponse(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        // Keyed on (request type, response type), not request type alone: IRequest<out TResponse>
        // is covariant, so a single request type can legally implement it for more than one
        // TResponse. A request-type-only key would let two [typeof(SameRequest)] entries collide
        // in this dictionary initializer — which doesn't throw, it just silently keeps whichever
        // one was added last (Dictionary indexer-set semantics), so the other TResponse's calls
        // would silently get the wrong handler back and fail an InvalidCastException downstream.
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            (global::System.Type Request, global::System.Type Response),");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.IRequest, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _requestResponseHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [(typeof({model.RequestType}), typeof({model.ResponseType}))] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IRequestHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IRequestDecorator.WithResponse");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // Task<{ResponseType}> is-a Task, no cast needed here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task<TResponse> SendAsync<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IRequest<TResponse> request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(request));");
        sb.AppendLine();
        sb.AppendLine("            if (_requestResponseHandlers.TryGetValue((request.GetType(), typeof(TResponse)), out var handler))");
        sb.AppendLine("                return (global::System.Threading.Tasks.Task<TResponse>)handler(_sp, request, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                NotDiscovered($\"IRequestHandler<{request.GetType()}, {typeof(TResponse)}>\"));");
        sb.AppendLine("        }");
    }

    private static void AppendSendStream(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        // Keyed on (request type, response type) — see AppendSendAsyncWithResponse: IStreamRequest<out
        // TResponse> is covariant too, so the same key-collision risk applies here.
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            (global::System.Type Request, global::System.Type Response),");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, object, " +
                      "global::System.Threading.CancellationToken, object>> _streamHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [(typeof({model.RequestType}), typeof({model.ResponseType}))] = static (sp, request, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})request;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IStreamRequestHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IStreamRequestDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // IAsyncEnumerable<{ResponseType}> is a reference type, boxed as object here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Collections.Generic.IAsyncEnumerable<TResponse> SendStream<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IStreamRequest<TResponse> request,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (request is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(request));");
        sb.AppendLine();
        sb.AppendLine("            return SendStreamCore<TResponse>(request, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine();
        // Everything past the null check — the dictionary lookup, the registered handler and
        // decorator's construction via DI, and any of a decorator's own eager (non-yield) body
        // before its next() call — is deferred until enumeration actually starts, matching the
        // documented "handling begins when enumeration starts" contract. Only a real
        // async-iterator method's compiler-generated state machine (yield/await foreach)
        // guarantees none of this runs before the caller's first MoveNextAsync().
        sb.AppendLine("        private async global::System.Collections.Generic.IAsyncEnumerable<TResponse> SendStreamCore<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IStreamRequest<TResponse> request,");
        sb.AppendLine("            [global::System.Runtime.CompilerServices.EnumeratorCancellation] global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!_streamHandlers.TryGetValue((request.GetType(), typeof(TResponse)), out var handler))");
        sb.AppendLine("                throw new global::System.InvalidOperationException(");
        sb.AppendLine("                    NotDiscovered($\"IStreamRequestHandler<{request.GetType()}, {typeof(TResponse)}>\"));");
        sb.AppendLine();
        sb.AppendLine("            var inner = (global::System.Collections.Generic.IAsyncEnumerable<TResponse>)handler(_sp, request, cancellationToken);");
        sb.AppendLine("            await foreach (var item in inner.WithCancellation(cancellationToken))");
        sb.AppendLine("                yield return item;");
        sb.AppendLine("        }");
    }

    private static void AppendSendAsyncCommand(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.ICommand, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _commandHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [typeof({model.RequestType})] = static (sp, command, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})command;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.ICommandHandler<{model.RequestType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.ICommandDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};");
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task SendAsync(");
        sb.AppendLine("            global::Davish.Sendr.ICommand command,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (command is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(command));");
        sb.AppendLine();
        sb.AppendLine("            if (_commandHandlers.TryGetValue(command.GetType(), out var handler))");
        sb.AppendLine("                return handler(_sp, command, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                NotDiscovered($\"ICommandHandler<{command.GetType()}>\"));");
        sb.AppendLine("        }");
    }

    private static void AppendSendAsyncCommandWithResponse(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        // Keyed on (command type, response type) — see AppendSendAsyncWithResponse: ICommand<out
        // TResponse> is covariant too, so the same key-collision risk applies here.
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            (global::System.Type Request, global::System.Type Response),");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.ICommand, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _commandResponseHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [(typeof({model.RequestType}), typeof({model.ResponseType}))] = static (sp, command, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})command;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.ICommandHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.ICommandDecorator.WithResponse");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // Task<{ResponseType}> is-a Task, no cast needed here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task<TResponse> SendAsync<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.ICommand<TResponse> command,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (command is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(command));");
        sb.AppendLine();
        sb.AppendLine("            if (_commandResponseHandlers.TryGetValue((command.GetType(), typeof(TResponse)), out var handler))");
        sb.AppendLine("                return (global::System.Threading.Tasks.Task<TResponse>)handler(_sp, command, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                NotDiscovered($\"ICommandHandler<{command.GetType()}, {typeof(TResponse)}>\"));");
        sb.AppendLine("        }");
    }

    private static void AppendSendAsyncQuery(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        // Keyed on (query type, response type) — see AppendSendAsyncWithResponse: IQuery<out
        // TResponse> is covariant too, so the same key-collision risk applies here.
        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            (global::System.Type Request, global::System.Type Response),");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, object, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>> _queryHandlers = new()");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            [(typeof({model.RequestType}), typeof({model.ResponseType}))] = static (sp, query, cancellationToken) =>");
            sb.AppendLine("            {");
            sb.AppendLine($"                var r = ({model.RequestType})query;");
            sb.AppendLine($"                var h = (global::Davish.Sendr.IQueryHandler<{model.RequestType}, {model.ResponseType}>)" +
                           $"sp.GetRequiredService<{model.HandlerType}>();");
            AppendDecoratorLocals(sb, model, "global::Davish.Sendr.IQueryDecorator");
            var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
            sb.AppendLine($"                return {call};"); // Task<{ResponseType}> is-a Task, no cast needed here.
            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task<TResponse> SendAsync<TResponse>(");
        sb.AppendLine("            global::Davish.Sendr.IQuery<TResponse> query,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (query is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(query));");
        sb.AppendLine();
        sb.AppendLine("            if (_queryHandlers.TryGetValue((query.GetType(), typeof(TResponse)), out var handler))");
        sb.AppendLine("                return (global::System.Threading.Tasks.Task<TResponse>)handler(_sp, query, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine("            throw new global::System.InvalidOperationException(");
        sb.AppendLine("                NotDiscovered($\"IQueryHandler<{query.GetType()}, {typeof(TResponse)}>\"));");
        sb.AppendLine("        }");
    }

    // Unlike every other handler kind, a notification type is expected to have any number of
    // handlers (including zero), so these are grouped by notification type into a
    // Dictionary<Type, Func<...>[]> rather than a Dictionary<Type, Func<...>> of exactly one.
    private static void AppendGeneratedPublisher(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("    internal sealed class GeneratedPublisher : global::Davish.Sendr.IPublisher");
        sb.AppendLine("    {");
        sb.AppendLine("        private readonly global::System.IServiceProvider _sp;");
        sb.AppendLine("        private readonly global::Davish.Sendr.NotificationRunMode _runMode;");
        sb.AppendLine();
        sb.AppendLine("        public GeneratedPublisher(global::System.IServiceProvider sp, global::Davish.Sendr.NotificationRunMode runMode)");
        sb.AppendLine("        {");
        sb.AppendLine("            _sp = sp;");
        sb.AppendLine("            _runMode = runMode;");
        sb.AppendLine("        }");
        sb.AppendLine();

        sb.AppendLine("        private static readonly global::System.Collections.Generic.Dictionary<");
        sb.AppendLine("            global::System.Type,");
        sb.AppendLine("            global::System.Func<global::System.IServiceProvider, global::Davish.Sendr.INotification, " +
                      "global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task>[]> _notificationHandlers = new()");
        sb.AppendLine("        {");

        foreach (var group in models.GroupBy(m => m.RequestType))
        {
            sb.AppendLine($"            [typeof({group.Key})] = new global::System.Func<global::System.IServiceProvider, " +
                          "global::Davish.Sendr.INotification, global::System.Threading.CancellationToken, " +
                          "global::System.Threading.Tasks.Task>[]");
            sb.AppendLine("            {");

            foreach (var model in group)
            {
                sb.AppendLine("                static (sp, notification, cancellationToken) =>");
                sb.AppendLine("                {");
                sb.AppendLine($"                    var r = ({model.RequestType})notification;");
                sb.AppendLine($"                    var h = (global::Davish.Sendr.INotificationHandler<{model.RequestType}>)" +
                               $"sp.GetRequiredService<{model.HandlerType}>();");
                AppendDecoratorLocals(sb, model, "global::Davish.Sendr.INotificationDecorator");
                var call = BuildComposedCall(model, "h.HandleAsync(r, cancellationToken)");
                sb.AppendLine($"                    return {call};");
                sb.AppendLine("                },");
            }

            sb.AppendLine("            },");
        }

        sb.AppendLine("        };");
        sb.AppendLine();

        sb.AppendLine("        public global::System.Threading.Tasks.Task PublishAsync(");
        sb.AppendLine("            global::Davish.Sendr.INotification notification,");
        sb.AppendLine("            global::System.Threading.CancellationToken cancellationToken)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (notification is null)");
        sb.AppendLine("                throw new global::System.ArgumentNullException(nameof(notification));");
        sb.AppendLine();
        sb.AppendLine("            if (!_notificationHandlers.TryGetValue(notification.GetType(), out var steps))");
        sb.AppendLine("                return global::System.Threading.Tasks.Task.CompletedTask;");
        sb.AppendLine();
        sb.AppendLine("            var bound = new global::System.Func<global::System.Threading.CancellationToken, " +
                      "global::System.Threading.Tasks.Task>[steps.Length];");
        sb.AppendLine("            for (var i = 0; i < steps.Length; i++)");
        sb.AppendLine("            {");
        sb.AppendLine("                var step = steps[i];");
        sb.AppendLine("                bound[i] = ct => step(_sp, notification, ct);");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine("            return _runMode == global::Davish.Sendr.NotificationRunMode.Parallel");
        sb.AppendLine("                ? global::Davish.Sendr.NotificationGroupRunner.RunParallelAsync(bound, cancellationToken)");
        sb.AppendLine("                : global::Davish.Sendr.NotificationGroupRunner.RunSequenceAsync(bound, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendNotificationOptionsGeneratedExtensions(StringBuilder sb, ImmutableArray<HandlerModel> models)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Source-generated Davish.Sendr.Notification registration. Discovers every");
        sb.AppendLine("    /// <c>INotificationHandler&lt;T&gt;</c> in this compilation and installs a reflection-free");
        sb.AppendLine("    /// <c>IPublisher</c> in their place. Generated by Davish.Sendr.Generators.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static class NotificationOptionsGeneratedExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Installs the generated, reflection-free <c>IPublisher</c> and registers every handler");
        sb.AppendLine("        /// (and <c>[Decorate&lt;...&gt;]</c> pipeline) discovered in this compilation. Every");
        sb.AppendLine("        /// notification type may have any number of handlers; among handlers of the same");
        sb.AppendLine("        /// notification, no ordering is guaranteed. Call from <c>AddSendrNotification</c>:");
        sb.AppendLine("        /// <c>services.AddSendrNotification(o =&gt; o.UseGenerators())</c>.");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        /// <param name=\"options\">The options being configured.</param>");
        sb.AppendLine("        /// <param name=\"configure\">");
        sb.AppendLine("        /// An optional callback to choose how handlers of the same notification run relative to");
        sb.AppendLine("        /// each other, via <c>x.RunAs(NotificationRunMode.Parallel)</c>. Defaults to");
        sb.AppendLine("        /// <see cref=\"global::Davish.Sendr.NotificationRunMode.Sequence\"/>.");
        sb.AppendLine("        /// </param>");
        sb.AppendLine("        public static global::Davish.Sendr.NotificationOptions UseGenerators(");
        sb.AppendLine("            this global::Davish.Sendr.NotificationOptions options,");
        sb.AppendLine("            global::System.Action<global::Davish.Sendr.GeneratedNotificationRunOptions>? configure = null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var runOptions = new global::Davish.Sendr.GeneratedNotificationRunOptions();");
        sb.AppendLine("            configure?.Invoke(runOptions);");
        sb.AppendLine();
        sb.AppendLine("            options.UsePublisher<global::Davish.Sendr.Generated.GeneratedPublisher>();");
        sb.AppendLine("            var services = options.Services;");
        sb.AppendLine("            services.AddSingleton(typeof(global::Davish.Sendr.NotificationRunMode), runOptions.RunMode);");
        sb.AppendLine();

        AppendHandlerAndDecoratorRegistrations(sb, models);

        sb.AppendLine();
        sb.AppendLine("            return options;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }

    private static void AppendDecoratorLocals(StringBuilder sb, HandlerModel model, string decoratorInterface)
    {
        for (var i = 0; i < model.Decorators.Length; i++)
        {
            sb.AppendLine($"                var d{i} = ({decoratorInterface})" +
                           $"sp.GetRequiredService<{model.Decorators[i].TypeName}>();");
        }
    }

    /// <summary>
    /// Wraps <paramref name="innermostCall"/> with the model's decorators, outermost-first,
    /// mirroring the ordering of <c>x.Decorator.With&lt;T&gt;()</c> chains: the first
    /// <c>[Decorate]</c> declared is the outermost layer and runs first.
    /// </summary>
    private static string BuildComposedCall(HandlerModel model, string innermostCall)
    {
        var call = innermostCall;
        for (var i = model.Decorators.Length - 1; i >= 0; i--)
            call = $"d{i}.HandleAsync(r, () => {call}, cancellationToken)";
        return call;
    }
}
